# LOOSE PARAMETERS - PLAY WITH THEM FREELY
FPS = 60
PAUSETIME = 3

# TIGHT PARAMETERS - STRUCTURAL CHANGE
WIDTH = 800
HEIGHT = 600
TILESIZE = 40
PLAY_HEIGHT = HEIGHT - TILESIZE


# CONSTANTS - NOT TO BE CHANGED
PLAYER1 = 0
PLAYER2 = 1
INVIS = -1

PLAYER1_HOR_AXIS = 6
PLAYER1_VER_AXIS = 7
PLAYER2_HOR_AXIS = 2
PLAYER2_VER_AXIS = 3

PLAYER1_X = 14
PLAYER2_X = 2